# Generated by Django 3.1.7 on 2021-02-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('assigned_players', models.TextField(null=True)),
                ('completed_reviews', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('ref_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(max_length=1000)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerevals.players')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playerevals.reviewer')),
            ],
        ),
    ]
